[api]
listen="0.0.0.0:11360"

[rpc]
host="http://203.86.232.107:8131"
admin="admin_qitmeer"
password="6qFQw!N7JgE8D.R"

[db]
# mysql | sqlserver
dbtype="mysql"
user="client"
password="Qitmeer@user.client"
address="203.86.236.25:3306"
dbname="mainnet_23_0317;"

[log]
# console=12 | file=11
mode=12
# debug=0 | info=1 | warn=2 | fail=3 | error=4 | email=5
level=0

[resources]
cpu-number=4
gc-percent=20

[qitmeer]
# 0.9|0.10
version="0.10"
network="mainnet"